# Generated by Django 4.1.5 on 2023-01-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=520, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('price_ttc', models.FloatField(blank=True, default=0.0, null=True)),
                ('description', models.TextField(max_length=2500)),
                ('image', models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/prod/')),
                ('stock', models.IntegerField(default=0)),
                ('marque_produit', models.CharField(default='', max_length=120)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
